/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <Stm32f0xx.h>
#include <STM32F0XX_GPIO_driver.h>

void delay(void)
{
	for(uint32_t i = 0 ; i < 500000 ; i ++); //16mhz
}

int main(void)
{
	GPIO_Handle_t GpioLed;
	GpioLed.pGPIOx = GPIOA;
	GpioLed.GPIO_PinConfig.GPIO_PinNummer = GPIO_PIN_NO_5;
	GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_Mode_OUT  ;
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_OP_SPEED_FAST   ;
	GpioLed.GPIO_PinConfig.GPIO_PinOpType = GPIO_OP_TYPR_PP;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	//GpioLed.GPIO_PinConfig.GPIO_PinOpType = GPIO_OP_TYPR_OD; //OPEN DRAIN MODE
	//GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PU; //PULL-UP RESİSTOR

	GPIO_periperalclockControl(GPIOA,ENABLE);

	GPIO_Inıt(&GpioLed);

	GpioLed.pGPIOx = GPIOA;


	while(1)
		{
			GPIO_ToggleOutputPin(GPIOA,GPIO_PIN_NO_5);
			 delay();
		}
		return 0;
}
